### ISSUE TITLE
CI is sloooow

### ISSUE THREAD

**Issue by axelboc** [mxcube/mxcube3#1424]
You've probably noticed it. Not sure if it's a temporary slow down or if it's something to do with the recent change to test all supported Python versions. https://github.com/mxcube/mxcubeweb/actions/runs/11069955541

![image](https://github.com/user-attachments/assets/973f9fa7-4a9e-4aca-9aed-98940a721100)

**Comment by marcus-oscarsson** [comment]
I think its temporary, it was quite quick earlier today. The pages build took forever though.

**Comment by fabcor-maxiv** [comment]
Nothing obvious on https://www.githubstatus.com/

**Comment by marcus-oscarsson** [comment]
Looks like the actions are stuck on
```
micromamba list
  /home/runner/micromamba-bin/micromamba list -r /home/runner/micromamba -n mxcubeweb
```

A bit strange, considering that is just listing the installed packages. It does not seem to matter if we are only running one python version or several simultaneously

**Comment by fabcor-maxiv** [comment]
There was a new major release of mamba and micromamba. Versions 2.0.0 for both. Maybe something broke.

We can try:
```yaml
- uses: mamba-org/setup-micromamba@v1
  with:
    micromamba-version: '1.5.10-0' # any version from https://github.com/mamba-org/micromamba-releases
```
