### ISSUE TITLE
Make 'Remember parameters between samples' default configurable

### ISSUE THREAD

**Issue by elmjag** [mxcube/mxcube3#1500]
MXCuBE have a setting `Remember parameters between samples`:

![image](https://github.com/user-attachments/assets/5f03f62c-88e4-4a8c-a3b5-f3dcf65c48f7)

The default value for this setting is hard-coded here:

https://github.com/mxcube/mxcubeweb/blob/542423c884ac74057f26e46b55cd055fd2ac84f1/mxcubeweb/app.py#L241

Currently, it is set to `False`, which is of cause opposite of what scientist here at MAXIV demand.

How about making this hard-coded value a configurable instead? I suggest adding a new section `settings` to `mxcube-web/ui.yaml` file. With following format:

```
settings:
 remember_parameters_between_samples:
   default: true
 some_other_setting:
   default: false
 yet_another_setting:
   default: true
```
  
What do you think?
